-- RSVP persistence for the Hanis & Nabil invitation on Neon PostgreSQL.
--
-- Run this once in the Neon SQL Editor before running /api/migrate-to-neon.
-- The Vercel Function uses a private DATABASE_URL; browsers never connect to
-- this database directly.

begin;

create table if not exists public.rsvp_entries (
  -- "by default" lets the one-time snapshot import preserve Supabase IDs.
  -- Normal RSVP inserts omit id and still use the identity sequence.
  id bigint generated by default as identity primary key,
  name text not null,
  phone_normalized text not null,
  phone_hash text not null unique,
  ip_hash text not null,
  attendance text not null,
  guest_count smallint not null default 0,
  wish text,
  wish_status text not null default 'published',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint rsvp_entries_name_length_check check (char_length(btrim(name)) between 2 and 80),
  constraint rsvp_entries_phone_format_check check (phone_normalized ~ E'^\\+[1-9][0-9]{7,14}$'),
  constraint rsvp_entries_phone_hash_format_check check (phone_hash ~ '^[a-f0-9]{64}$'),
  constraint rsvp_entries_ip_hash_format_check check (ip_hash ~ '^[a-f0-9]{64}$'),
  constraint rsvp_entries_attendance_check check (attendance in ('hadir', 'tidak_hadir')),
  constraint rsvp_entries_guest_count_check check (
    (attendance = 'hadir' and guest_count between 1 and 10)
    or (attendance = 'tidak_hadir' and guest_count = 0)
  ),
  constraint rsvp_entries_wish_length_check check (wish is null or char_length(wish) <= 250),
  constraint rsvp_entries_wish_status_check check (wish_status in ('published', 'pending'))
);

create table if not exists public.rsvp_submission_events (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  created_at timestamptz not null default now(),
  constraint rsvp_submission_events_ip_hash_format_check check (ip_hash ~ '^[a-f0-9]{64}$')
);

-- One short-lived counter per anonymous, hashed IP. This prevents the public
-- wishes endpoint from being scraped without retaining raw IP addresses.
create table if not exists public.rsvp_read_rate_limits (
  ip_hash text primary key,
  window_started_at timestamptz not null default now(),
  read_count smallint not null default 0,
  updated_at timestamptz not null default now(),
  constraint rsvp_read_rate_limits_ip_hash_format_check check (ip_hash ~ '^[a-f0-9]{64}$'),
  constraint rsvp_read_rate_limits_read_count_check check (read_count >= 0)
);

create index if not exists rsvp_entries_published_wishes_idx
  on public.rsvp_entries (updated_at desc)
  where wish_status = 'published' and wish is not null;

create index if not exists rsvp_submission_events_ip_created_idx
  on public.rsvp_submission_events (ip_hash, created_at desc);

create index if not exists rsvp_read_rate_limits_updated_idx
  on public.rsvp_read_rate_limits (updated_at);

-- The database URL belongs only in Vercel environment variables. RLS protects
-- the tables from future low-privilege roles; the database owner used by the
-- server-side function can still execute the private SQL functions below.
alter table public.rsvp_entries enable row level security;
alter table public.rsvp_submission_events enable row level security;
alter table public.rsvp_read_rate_limits enable row level security;

revoke all on table public.rsvp_entries from public;
revoke all on table public.rsvp_submission_events from public;
revoke all on table public.rsvp_read_rate_limits from public;
revoke all on sequence public.rsvp_entries_id_seq from public;
revoke all on sequence public.rsvp_submission_events_id_seq from public;

create or replace function public.set_rsvp_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists rsvp_entries_set_updated_at on public.rsvp_entries;
create trigger rsvp_entries_set_updated_at
before update on public.rsvp_entries
for each row
execute function public.set_rsvp_updated_at();

create or replace function public.consume_rsvp_read_budget(p_ip_hash text)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  within_limit boolean;
begin
  insert into public.rsvp_read_rate_limits as limits (
    ip_hash,
    window_started_at,
    read_count,
    updated_at
  )
  values (p_ip_hash, now(), 1, now())
  on conflict (ip_hash) do update
     set read_count = case
           when limits.window_started_at <= now() - interval '1 minute' then 1
           else limits.read_count + 1
         end,
         window_started_at = case
           when limits.window_started_at <= now() - interval '1 minute' then now()
           else limits.window_started_at
         end,
         updated_at = now()
  returning read_count <= 30 into within_limit;

  if not coalesce(within_limit, false) then
    raise exception 'rsvp_read_rate_limit' using errcode = 'P0001';
  end if;
end;
$$;

create or replace function public.submit_rsvp(
  p_name text,
  p_phone_normalized text,
  p_phone_hash text,
  p_ip_hash text,
  p_attendance text,
  p_guest_count integer,
  p_wish text,
  p_wish_status text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  recent_submission_count integer;
begin
  -- Serialise requests per anonymous IP hash so the three-per-ten-minute limit
  -- remains correct even when several requests arrive at the same instant.
  perform pg_advisory_xact_lock(pg_catalog.hashtext(p_ip_hash));

  select count(*)
    into recent_submission_count
    from public.rsvp_submission_events
   where ip_hash = p_ip_hash
     and created_at > now() - interval '10 minutes';

  if recent_submission_count >= 3 then
    raise exception 'rsvp_rate_limit' using errcode = 'P0001';
  end if;

  insert into public.rsvp_submission_events (ip_hash)
  values (p_ip_hash);

  insert into public.rsvp_entries (
    name,
    phone_normalized,
    phone_hash,
    ip_hash,
    attendance,
    guest_count,
    wish,
    wish_status
  )
  values (
    p_name,
    p_phone_normalized,
    p_phone_hash,
    p_ip_hash,
    p_attendance,
    p_guest_count,
    p_wish,
    p_wish_status
  )
  on conflict (phone_hash) do update
     set name = excluded.name,
         phone_normalized = excluded.phone_normalized,
         ip_hash = excluded.ip_hash,
         attendance = excluded.attendance,
         guest_count = excluded.guest_count,
         wish = excluded.wish,
         wish_status = excluded.wish_status;

  return jsonb_build_object('ok', true);
end;
$$;

drop function if exists public.get_public_rsvp();
drop function if exists public.get_public_rsvp(text);

create function public.get_public_rsvp(p_ip_hash text)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  result jsonb;
begin
  perform public.consume_rsvp_read_budget(p_ip_hash);

  with summary as (
    select
      count(*) filter (where attendance = 'hadir') as hadir,
      coalesce(sum(guest_count) filter (where attendance = 'hadir'), 0) as "tetamuHadir",
      count(*) filter (where attendance = 'tidak_hadir') as "tidakHadir"
    from public.rsvp_entries
  ),
  latest_wishes as (
    select name, wish, updated_at
    from public.rsvp_entries
    where wish_status = 'published'
      and wish is not null
      and btrim(wish) <> ''
    order by updated_at desc
    limit 100
  )
  select jsonb_build_object(
    'summary', jsonb_build_object(
      'hadir', summary.hadir,
      'tetamuHadir', summary."tetamuHadir",
      'tidakHadir', summary."tidakHadir"
    ),
    'wishes', coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'name', latest_wishes.name,
            'wish', latest_wishes.wish,
            'createdAt', latest_wishes.updated_at
          )
          order by latest_wishes.updated_at desc
        )
        from latest_wishes
      ),
      '[]'::jsonb
    )
  )
    into result
  from summary;

  return result;
end;
$$;

-- This is deliberately an owner-only, one-time migration primitive. It replaces
-- all three RSVP table snapshots in one transaction and preserves source IDs and
-- timestamps. It returns aggregate counts only, never RSVP names, phones or IP
-- hashes. Any failing constraint aborts the complete replacement automatically.
create or replace function public.replace_rsvp_snapshot(
  p_entries jsonb,
  p_submission_events jsonb,
  p_read_rate_limits jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_entries_count bigint;
  v_submission_events_count bigint;
  v_read_rate_limits_count bigint;
  v_hadir_count bigint;
  v_tetamu_hadir_count bigint;
  v_tidak_hadir_count bigint;
  v_published_wishes_count bigint;
begin
  if p_entries is null or jsonb_typeof(p_entries) <> 'array'
    or p_submission_events is null or jsonb_typeof(p_submission_events) <> 'array'
    or p_read_rate_limits is null or jsonb_typeof(p_read_rate_limits) <> 'array' then
    raise exception 'invalid_rsvp_snapshot' using errcode = '22023';
  end if;

  -- A named advisory lock keeps simultaneous authorized migration attempts from
  -- interleaving. The table locks make the replacement itself a true snapshot.
  -- A short timeout makes an accidental run during live Neon writes fail and
  -- roll back instead of holding the invitation API indefinitely.
  perform pg_advisory_xact_lock(pg_catalog.hashtext('rsvp_snapshot_import_v1'));
  perform pg_catalog.set_config('lock_timeout', '5s', true);
  lock table public.rsvp_entries, public.rsvp_submission_events, public.rsvp_read_rate_limits
    in access exclusive mode;

  truncate table public.rsvp_entries, public.rsvp_submission_events, public.rsvp_read_rate_limits
    restart identity;

  insert into public.rsvp_entries (
    id,
    name,
    phone_normalized,
    phone_hash,
    ip_hash,
    attendance,
    guest_count,
    wish,
    wish_status,
    created_at,
    updated_at
  )
  select
    source.id,
    source.name,
    source.phone_normalized,
    source.phone_hash,
    source.ip_hash,
    source.attendance,
    source.guest_count,
    source.wish,
    source.wish_status,
    source.created_at,
    source.updated_at
  from jsonb_to_recordset(p_entries) as source(
    id bigint,
    name text,
    phone_normalized text,
    phone_hash text,
    ip_hash text,
    attendance text,
    guest_count smallint,
    wish text,
    wish_status text,
    created_at timestamptz,
    updated_at timestamptz
  )
  order by source.id;

  insert into public.rsvp_submission_events (id, ip_hash, created_at)
  select source.id, source.ip_hash, source.created_at
  from jsonb_to_recordset(p_submission_events) as source(
    id bigint,
    ip_hash text,
    created_at timestamptz
  )
  order by source.id;

  insert into public.rsvp_read_rate_limits (
    ip_hash,
    window_started_at,
    read_count,
    updated_at
  )
  select
    source.ip_hash,
    source.window_started_at,
    source.read_count,
    source.updated_at
  from jsonb_to_recordset(p_read_rate_limits) as source(
    ip_hash text,
    window_started_at timestamptz,
    read_count smallint,
    updated_at timestamptz
  )
  order by source.ip_hash;

  if exists (select 1 from public.rsvp_entries) then
    perform pg_catalog.setval(
      pg_catalog.pg_get_serial_sequence('public.rsvp_entries', 'id'),
      (select max(id) from public.rsvp_entries),
      true
    );
  else
    perform pg_catalog.setval(
      pg_catalog.pg_get_serial_sequence('public.rsvp_entries', 'id'),
      1,
      false
    );
  end if;

  if exists (select 1 from public.rsvp_submission_events) then
    perform pg_catalog.setval(
      pg_catalog.pg_get_serial_sequence('public.rsvp_submission_events', 'id'),
      (select max(id) from public.rsvp_submission_events),
      true
    );
  else
    perform pg_catalog.setval(
      pg_catalog.pg_get_serial_sequence('public.rsvp_submission_events', 'id'),
      1,
      false
    );
  end if;

  select count(*) into v_entries_count from public.rsvp_entries;
  select count(*) into v_submission_events_count from public.rsvp_submission_events;
  select count(*) into v_read_rate_limits_count from public.rsvp_read_rate_limits;
  select
    count(*) filter (where attendance = 'hadir'),
    coalesce(sum(guest_count) filter (where attendance = 'hadir'), 0),
    count(*) filter (where attendance = 'tidak_hadir'),
    count(*) filter (where wish_status = 'published' and wish is not null and btrim(wish) <> '')
    into v_hadir_count, v_tetamu_hadir_count, v_tidak_hadir_count, v_published_wishes_count
  from public.rsvp_entries;

  return jsonb_build_object(
    'entries', v_entries_count,
    'submissionEvents', v_submission_events_count,
    'readRateLimits', v_read_rate_limits_count,
    'summary', jsonb_build_object(
      'hadir', v_hadir_count,
      'tetamuHadir', v_tetamu_hadir_count,
      'tidakHadir', v_tidak_hadir_count,
      'publishedWishes', v_published_wishes_count
    )
  );
end;
$$;

revoke all on function public.set_rsvp_updated_at() from public;
revoke all on function public.consume_rsvp_read_budget(text) from public;
revoke all on function public.submit_rsvp(text, text, text, text, text, integer, text, text)
  from public;
revoke all on function public.get_public_rsvp(text) from public;
revoke all on function public.replace_rsvp_snapshot(jsonb, jsonb, jsonb) from public;

commit;
