-- RSVP persistence for the Hani & Nabil invitation on Neon PostgreSQL.
-- New RSVP submissions intentionally do not collect or retain phone numbers.
--
-- Run this once in the Neon SQL Editor before deploying the RSVP API.
-- The Vercel Function uses a private DATABASE_URL; browsers never connect to
-- this database directly.

begin;

create table if not exists public.rsvp_entries (
  -- "by default" lets the one-time snapshot import preserve Supabase IDs.
  -- Normal RSVP inserts omit id and still use the identity sequence.
  id bigint generated by default as identity primary key,
  name text not null,
  ip_hash text not null,
  attendance text not null,
  guest_count smallint not null default 0,
  wish text,
  wish_status text not null default 'published',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint rsvp_entries_name_length_check check (char_length(btrim(name)) between 2 and 80),
  constraint rsvp_entries_ip_hash_format_check check (ip_hash ~ '^[a-f0-9]{64}$'),
  constraint rsvp_entries_attendance_check check (attendance in ('hadir', 'tidak_hadir')),
  constraint rsvp_entries_guest_count_check check (
    (attendance = 'hadir' and guest_count between 1 and 10)
    or (attendance = 'tidak_hadir' and guest_count = 0)
  ),
  constraint rsvp_entries_wish_length_check check (wish is null or char_length(wish) <= 250),
  constraint rsvp_entries_wish_status_check check (wish_status in ('published', 'pending'))
);

create table if not exists public.rsvp_submission_events (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  created_at timestamptz not null default now(),
  constraint rsvp_submission_events_ip_hash_format_check check (ip_hash ~ '^[a-f0-9]{64}$')
);

-- One short-lived counter per anonymous, hashed IP. This prevents the public
-- wishes endpoint from being scraped without retaining raw IP addresses.
create table if not exists public.rsvp_read_rate_limits (
  ip_hash text primary key,
  window_started_at timestamptz not null default now(),
  read_count smallint not null default 0,
  updated_at timestamptz not null default now(),
  constraint rsvp_read_rate_limits_ip_hash_format_check check (ip_hash ~ '^[a-f0-9]{64}$'),
  constraint rsvp_read_rate_limits_read_count_check check (read_count >= 0)
);

create index if not exists rsvp_entries_published_wishes_idx
  on public.rsvp_entries (updated_at desc)
  where wish_status = 'published' and wish is not null;

create index if not exists rsvp_submission_events_ip_created_idx
  on public.rsvp_submission_events (ip_hash, created_at desc);

create index if not exists rsvp_read_rate_limits_updated_idx
  on public.rsvp_read_rate_limits (updated_at);

-- The database URL belongs only in Vercel environment variables. RLS protects
-- the tables from future low-privilege roles; the database owner used by the
-- server-side function can still execute the private SQL functions below.
alter table public.rsvp_entries enable row level security;
alter table public.rsvp_submission_events enable row level security;
alter table public.rsvp_read_rate_limits enable row level security;

revoke all on table public.rsvp_entries from public;
revoke all on table public.rsvp_submission_events from public;
revoke all on table public.rsvp_read_rate_limits from public;
revoke all on sequence public.rsvp_entries_id_seq from public;
revoke all on sequence public.rsvp_submission_events_id_seq from public;

create or replace function public.set_rsvp_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists rsvp_entries_set_updated_at on public.rsvp_entries;
create trigger rsvp_entries_set_updated_at
before update on public.rsvp_entries
for each row
execute function public.set_rsvp_updated_at();

create or replace function public.consume_rsvp_read_budget(p_ip_hash text)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  within_limit boolean;
begin
  insert into public.rsvp_read_rate_limits as limits (
    ip_hash,
    window_started_at,
    read_count,
    updated_at
  )
  values (p_ip_hash, now(), 1, now())
  on conflict (ip_hash) do update
     set read_count = case
           when limits.window_started_at <= now() - interval '1 minute' then 1
           else limits.read_count + 1
         end,
         window_started_at = case
           when limits.window_started_at <= now() - interval '1 minute' then now()
           else limits.window_started_at
         end,
         updated_at = now()
  returning read_count <= 30 into within_limit;

  if not coalesce(within_limit, false) then
    raise exception 'rsvp_read_rate_limit' using errcode = 'P0001';
  end if;
end;
$$;

create or replace function public.submit_rsvp(
  p_name text,
  p_ip_hash text,
  p_attendance text,
  p_guest_count integer,
  p_wish text,
  p_wish_status text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  recent_submission_count integer;
begin
  -- Serialise requests per anonymous IP hash so the three-per-ten-minute limit
  -- remains correct even when several requests arrive at the same instant.
  perform pg_advisory_xact_lock(pg_catalog.hashtext(p_ip_hash));

  select count(*)
    into recent_submission_count
    from public.rsvp_submission_events
   where ip_hash = p_ip_hash
     and created_at > now() - interval '10 minutes';

  if recent_submission_count >= 3 then
    raise exception 'rsvp_rate_limit' using errcode = 'P0001';
  end if;

  insert into public.rsvp_submission_events (ip_hash)
  values (p_ip_hash);

  -- Without a contact field there is no reliable person-level identifier.
  -- Each accepted form submission is kept as its own RSVP entry.
  insert into public.rsvp_entries (
    name,
    ip_hash,
    attendance,
    guest_count,
    wish,
    wish_status
  )
  values (
    p_name,
    p_ip_hash,
    p_attendance,
    p_guest_count,
    p_wish,
    p_wish_status
  );
  return jsonb_build_object('ok', true);
end;
$$;

drop function if exists public.get_public_rsvp();
drop function if exists public.get_public_rsvp(text);

create function public.get_public_rsvp(p_ip_hash text)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  result jsonb;
begin
  perform public.consume_rsvp_read_budget(p_ip_hash);

  with summary as (
    select
      count(*) filter (where attendance = 'hadir') as hadir,
      coalesce(sum(guest_count) filter (where attendance = 'hadir'), 0) as "tetamuHadir",
      count(*) filter (where attendance = 'tidak_hadir') as "tidakHadir"
    from public.rsvp_entries
  ),
  latest_wishes as (
    select name, wish, updated_at
    from public.rsvp_entries
    where wish_status = 'published'
      and wish is not null
      and btrim(wish) <> ''
    order by updated_at desc
    limit 100
  )
  select jsonb_build_object(
    'summary', jsonb_build_object(
      'hadir', summary.hadir,
      'tetamuHadir', summary."tetamuHadir",
      'tidakHadir', summary."tidakHadir"
    ),
    'wishes', coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'name', latest_wishes.name,
            'wish', latest_wishes.wish,
            'createdAt', latest_wishes.updated_at
          )
          order by latest_wishes.updated_at desc
        )
        from latest_wishes
      ),
      '[]'::jsonb
    )
  )
    into result
  from summary;

  return result;
end;
$$;

revoke all on function public.set_rsvp_updated_at() from public;
revoke all on function public.consume_rsvp_read_budget(text) from public;
revoke all on function public.submit_rsvp(text, text, text, integer, text, text)
  from public;
revoke all on function public.get_public_rsvp(text) from public;

commit;
